/**
 * Fiserv response codes as returned by WeVend (`respCode` / `returnCode`).
 *
 * Transcribed from WeVend's integration FAQ (WePay API Gateway v3.2.2, Appendix A —
 * Fiserv Response Codes, (c) 2024 Fiserv). Kept in the repo so a code in a log or a
 * support ticket can be read without opening a PDF.
 *
 * Two separate concerns live here on purpose:
 *  - `RESPONSE_CODES` is the raw meaning, for logs, audits and support.
 *  - `donorMessage()` is what a DONOR may be told, which is deliberately not the
 *    same thing: telling someone their card was flagged as counterfeit or
 *    suspected fraud coaches card testing and is not ours to disclose. Those
 *    collapse into the generic decline.
 */

export const RESPONSE_CODES: Record<string, string> = {
  "000": "Approve",
  "001": "Schema Validation Error",
  "002": "Approve for partial amount",
  "003": "Approve VIP",
  "100": "Do not honor",
  "101": "Expired card",
  "102": "Suspected fraud",
  "103": "Unable to process TeleCheck recurring transaction with this payment type (not associated with insufficient or uncollected funds)",
  "104": "Restricted card",
  "105": "Call acquirer's security department",
  "106": "Allowable PIN tries exceeded",
  "107": "Call for authorization",
  "108": "Refer to issuer's special conditions",
  "109": "Invalid merchant. The merchant is not in the merchant database or the merchant is not permitted to use this particular card",
  "110": "Invalid amount",
  "111": "Invalid Host Totals Date",
  "112": "DES Encryption not allowed from the device / terminal",
  "113": "Host Totals are Incomplete",
  "114": "Invalid account type",
  "115": "Invalid HIP Amount",
  "116": "Not sufficient funds",
  "117": "Incorrect PIN or PIN length error",
  "118": "No card record",
  "119": "Transaction not permitted to cardholder",
  "120": "Transaction not permitted to terminal",
  "121": "Exceeds withdrawal amount limit",
  "122": "Security violation",
  "123": "Exceeds withdrawal frequency limit",
  "124": "Violation of law",
  "129": "Suspected counterfeit card",
  "130": "Invalid terminal",
  "131": "Invalid account number",
  "132": "Unmatched card expiry date",
  "133": "The TPP ID was not found",
  "134": "Not sufficient funds",
  "135": "Invalid Country Code",
  "150": "Invalid merchant set up",
  "151": "Activation failed",
  "152": "Exceeds limit",
  "153": "Already redeemed",
  "154": "Over monthly limit",
  "155": "Recharge amount exceeded",
  "156": "Max number of recharges exceeded",
  "157": "Invalid entry",
  "208": "Lost Card / Lost Check",
  "209": "Stolen card",
  "211": "Invalid SKU number",
  "212": "Missing conditional data",
  "213": "Invalid account number for card type",
  "214": "Invalid payment type/card type for merchant ID",
  "215": "Invalid transaction for Merchant ID",
  "216": "Invalid TransArmor request. Not supported for given Payment Type, or Merchant is not enabled for Transarmor",
  "217": "Missing or invalid secure payment data",
  "218": "Merchant ID not enabled for Secure Code",
  "219": "Invalid Merchant Category Code",
  "220": "Customer service phone number missing",
  "221": "Merchant not enabled for soft descriptors, account updater or optimization processing",
  "222": "Partial auth not allowed",
  "223": "Customer under 18 years old",
  "224": "Account blocked — possible compromise",
  "225": "Bill-to address does not match ship-to",
  "226": "Invalid preapproval number",
  "227": "Invalid email address",
  "228": "Need more ID — request full SSN",
  "229": "Previously declined/closed account",
  "230": "One time stop payment requested by cardholder",
  "231": "Stop payment requested for all payments",
  "232": "Stop all payments — account closed",
  "233": "Auth response date not valid",
  "234": "Issuance under minimum amount",
  "235": "Outstanding auth — funds on hold",
  "236": "Activation amount incorrect",
  "237": "Deny — new card issued",
  "238": "BIN blocked",
  "242": "Customer opt-out",
  "243": "Institution does not accept ACH payments",
  "244": "Original transaction not approved",
  "245": "Invalid MICR data",
  "246": "Declined due to high risk",
  "247": "Declined due to stand-in rules",
  "248": "Conditional Approval — Hold shipping for 24 hours",
  "250": "Re-authorization request is declined. Original Auth could not be found",
  "251": "Re-authorization request is declined. The customer account number, merchant id, or amount did not match the original authorization",
  "252": "Re-authorization request is declined. The amount significantly exceeds the original request amount",
  "253": "Re-authorization request is declined. The timeframes for re-authorization have been exceeded",
  "254": "Counter Offer to Supply Personal Guaranty",
  "300": "Invalid EAN or SCV",
  "301": "Lock has expired on prepaid card",
  "302": "Account closed. The account was closed, probably because the account balance was $0.00",
  "303": "Unknown account. The account could not be located or the account does not exist in the account table",
  "304": "Inactive account. The account has not been activated by an approved location",
  "308": "Already active. The card is already active and does not need to be reactivated",
  "311": "Not lost or stolen",
  "315": "Bad mag stripe. The mag stripe could not be parsed for account information",
  "316": "Incorrect location. There was a problem with the merchant location",
  "317": "Max balance exceeded. The transaction, if completed, would cause the account balance to be exceeded by the max_balance as specified in the promotion. Some merchants set the max_balance to a value twice the max transaction amount",
  "318": "Invalid amount. There was a problem with the amount field in the transaction format — more or less than min/max amounts specified in the promotion for that transaction",
  "319": "Invalid clerk. The clerk field was either missing, when required, or the content did not match the requirements",
  "320": "Invalid password",
  "321": "Invalid new password. The new password does not meet the minimum security criteria",
  "322": "Exceeded account reloads. The clerk/user/location was only permitted to reload some number of accounts. That number was exceeded. (See your Business Manager in order to extend this limit.)",
  "323": "Password retry exceeded. The user account has been frozen because the user attempted access and was denied. Seek management assistance",
  "326": "Incorrect transaction version or format number for POS transactions",
  "327": "Request not permitted by this account",
  "328": "Request not permitted by this merchant location",
  "329": "Bad_repay_date",
  "330": "Bad checksum. The checksum provided is incorrect",
  "331": "Balance not available (denial). Due to an internal Fiserv Prepaid Closed Loop issue, information from this account could not be retrieved",
  "332": "Account locked",
  "333": "No previous transaction. The void or reversal transaction could not be matched to a previous (original) transaction. In the case of a redemption, the corresponding locking transaction could not be identified",
  "334": "Already reversed",
  "336": "Bad Authorization ID. The Authorization ID test failed",
  "337": "Too many transactions requested",
  "338": "No transactions available/no more transactions available. There are no transactions for this account or there are no transactions as determined by the specified first transaction number",
  "339": "Transaction history not available",
  "340": "New password required",
  "341": "Invalid status change. The status change requested (e.g. lost/stolen, freeze active card) cannot be performed",
  "342": "Void of activation after account activity",
  "343": "No phone service. Attempted a calling card transaction on an account which is not configured for calling card activity",
  "344": "Internet access disabled",
  "345": "Invalid Date or Time",
  "350": "Additional customer authentication required or, Customer Authentication Required (Decline — Discover only)",
  "351": "Customer PIN authentication required",
  "355": "Invalid currency. The provided currency is invalid",
  "356": "Currency Not Supported",
  "357": "Currency conversion error",
  "359": "The terminal transaction number did not match (on a void or reversal)",
  "367": "Target embossed card entered and Transaction count entered do not match",
  "368": "No account link",
  "369": "Invalid time zone",
  "370": "Account on hold or subscriber not active",
  "372": "Promo location restricted",
  "373": "Invalid Card Account",
  "374": "Product code(s) restricted",
  "375": "Bad Post Date. The Post Date is not a valid date",
  "376": "Account status is void lock",
  "377": "Already active and reloadable",
  "378": "Account is Purged. The Account record was purged from the database",
  "380": "Bulk activation error",
  "381": "Bulk activation un-attempted error",
  "382": "Bulk activation package amount error",
  "383": "Store location zero not allowed",
  "384": "Account row locked",
  "385": "Accepted but not yet processed",
  "402": "TransArmor Service Unavailable",
  "403": "TransArmor Invalid Token or Account Number",
  "404": "TransArmor Key Error",
  "414": "Void/Full Reversal request unable to process due to network cut-off window elapsed. A Refund transaction is necessary to reconcile the cardholder's account. Applicable to Debit networks only.",
  "430": "Prepaid Card Amount Over EU AMLD (Anti-Money Laundering Directive) Limit",
  "500": "Decline",
  "501": "Date of Birth Error for Check Processing",
  "502": "Invalid State Code",
  "503": "New Account Information",
  "504": "Do not try again",
  "505": "Please retry",
  "506": "Invalid Checking Account Number",
  "507": "New Account Information available",
  "508": "Try again later — Declined: Association's payment cancellation advice code provided. Applies to recurring authorizations only. These are examples of what may have occurred: the account is over the credit limit try again in 72 hours.",
  "509": "Do not try again — Applies to recurring authorizations only. The card has expired",
  "510": "New Account Information — Applies to recurring authorizations only. The card has expired.",
  "511": "Try again later — Applies to recurring authorizations only. The card has expired. Get the new expiration date and try again.",
  "512": "Service not allowed or invalid surcharge amount",
  "513": "Decline. Transaction not permitted to acquirer or terminal.",
  "514": "Do not try again — Applies to recurring authorizations only. There was security violation.",
  "515": "Declined. No term record on Fiserv system",
  "516": "Please retry — Reasons for this error are one of the following: Format Error, Unable to route transaction, Switch or issuer unavailable, System Busy, Timeout",
  "517": "CVV2 Declined",
  "518": "Invalid account/date or sales date in future",
  "519": "Invalid Effective Date",
  "520": "Reversal Rejected. Do not try again.",
  "521": "Enter lesser amount",
  "522": "Cash Back greater than total Transaction amount",
  "523": "Crypto box is offline",
  "524": "Debit Switch unavailable Timeout Retry — Communications link to debit/EBT network gateway is down or responded with a “System Malfunction (96)” message",
  "525": "Debit/EBT network gateway cannot get through to the ISSUER.",
  "526": "Undefined Card — Debit/EBT network gateway cannot route card based on Merchant Entitlement",
  "527": "Network Response indicates that Merchant ID / SE is invalid",
  "528": "Debit/EBT transaction count exceeds pre-determined limit in specified time/ Withdrawal limit exceeded.",
  "529": "Resubmission of transaction violates debit/EBT network frequency",
  "530": "The authorizing network has a problem decrypting the cryptogram in the request",
  "531": "Retry with 3DS data",
  "532": "The DUKPT Base Derivation key is missing or incorrect in the PIN pad, PIN key synchronization error, or Master session PIN key is missing.",
  "533": "Invalid encryption key offset sent by merchant",
  "534": "Invalid master session key id sent by merchant",
  "539": "No Checking Account",
  "540": "Edit Honor",
  "541": "No Savings Account",
  "542": "DUKPT: An error while processing the PIN block that is not related to the point-of-sale equipment. Contact the Help Desk for assistance.",
  "550": "Invalid Vehicle",
  "551": "Invalid Driver",
  "552": "Invalid Product",
  "553": "Exceeds transaction total limit per product class",
  "554": "Over daily limit",
  "555": "Invalid Date/Time",
  "556": "Exceeds quantity",
  "557": "Invalid prompt entry",
  "558": "Invalid Track 2 data",
  "559": "Voyager ID problem",
  "560": "Invalid Odometer",
  "561": "Invalid Restriction Code",
  "562": "Pay at pump not allowed",
  "563": "Over fuel limit",
  "564": "Over cash limit",
  "565": "Fuel price error",
  "566": "Y or N required",
  "567": "Over repair limit",
  "568": "Over additive limit",
  "569": "Invalid user",
  "570": "Before 1400 and can't cut. Wait until 2:00 pm Eastern.",
  "571": "Cut time too close to 1400",
  "572": "Checker/Manager not found",
  "573": "Security insufficient",
  "574": "No transaction security record",
  "575": "Insufficient data",
  "576": "Merchant has mail pending",
  "577": "No messages pending",
  "578": "The Visa OCT / MasterCard MoneySend activity has exceeded preset transaction count or amount limit within a rolling 24-hour period for given merchant.",
  "579": "The Visa OCT / MasterCard MoneySend activity has exceeded preset transaction count or amount limit within a rolling 7-day period for given merchant.",
  "580": "The Visa OCT / MasterCard MoneySend activity has exceeded preset transaction count or amount limit within a rolling 30-day period for given merchant.",
  "581": "The Visa OCT / MasterCard MoneySend Funding activity has exceeded preset transaction count or amount limit within a rolling 24-hour period for this account number.",
  "582": "The Visa OCT / MasterCard MoneySend Funding activity has exceeded preset transaction count or amount limit within a rolling 7-day period for this account number.",
  "583": "The Visa OCT / MasterCard MoneySend Funding activity has exceeded preset transaction count or amount limit within a rolling 30-day period for this account number.",
  "584": "The Visa OCT / MasterCard MoneySend Payment activity has exceeded preset transaction count or amount limit within a rolling 24-hour period for this account number.",
  "585": "The Visa OCT / MasterCard MoneySend Payment activity has exceeded preset transaction count or amount limit within a rolling 7-day period for this account number.",
  "586": "The Visa OCT / MasterCard MoneySend Payment activity has exceeded preset transaction count or amount limit within a rolling 30-day period for this account number.",
  "587": "The single transaction amount limit was exceeded for a Visa OCT/ MasterCard MoneySend transaction for given merchant.",
  "588": "All Visa OCT / MasterCard MoneySend transactions are blocked for a rolling 24 hour period, or 7 day period (current and prior 6 days), or 30 day period (current and prior 29 days) for given merchant",
  "601": "Invalid Batch Number/ Invalid Batch ID or Invalid OpenBatch",
  "602": "No Open Batch",
  "603": "Close Unavailable",
  "604": "Close Not Valid",
  "701": "Approved EMV Key Load",
  "702": "EMV Key Download Error",
  "703": "Approved EMV Key Load, more key load data pending",
  "704": "Pick Up Card",
  "708": "Honor With Authentication",
  "721": "Invalid ZIP Code",
  "722": "Invalid value in the field / Host Totals Declined",
  "723": "Driver's License or ID is Required",
  "724": "Referred — Not Active",
  "726": "Unable to Locate Record On File",
  "727": "Refer — Call Authorization",
  "728": "Referred — Skip Trace Info",
  "729": "Hard Negative Info On File",
  "731": "Rejected Lost/Stolen Checks",
  "740": "Totals Unavailable",
  "767": "Hard Capture; Pick Up",
  "771": "Amount Too Large",
  "772": "Duplicate Return",
  "773": "Unsuccessful",
  "774": "Duplicate Reversal",
  "775": "Subsystem Unavailable",
  "776": "Duplicate Completion",
  "782": "Count Exceeds Limit",
  "785": "No reason to decline — applicable to $0.00 verification requests and may be returned on Online Refund responses. Should be treated as an approval.",
  "790": "Not approved. Used only in Visa bill/recurring payment. Merchant must not resubmit same transaction but may continue billing process in subsequent billing period.",
  "791": "Not approved. Used only in Visa bill/recurring payment. Merchant must stop recurring payment requests.",
  "792": "See attendant.",
  "800": "Deferred authorization not cancelled",
  "801": "Over merchandise limit",
  "802": "Imprint card",
  "803": "Not on file",
  "804": "Fuel only",
  "805": "Velocity exceeded",
  "806": "Authorization ID needed",
  "807": "Over non-fuel limit",
  "808": "Invalid location",
  "809": "Over card velocity count",
  "810": "Over card velocity amount",
  "811": "Over issuer velocity count",
  "812": "Over issuer velocity amount",
  "813": "Over merchant daily velocity count",
  "814": "Over merchant daily velocity amount",
  "815": "Over merchant daily velocity both",
  "816": "Over merchant product velocity amount",
  "817": "Over merchant product velocity count",
  "818": "Over merchant product velocity both",
  "819": "Over chain daily velocity count",
  "820": "Over chain daily velocity amount",
  "821": "Over chain daily velocity both",
  "822": "Over chain product velocity count",
  "823": "Over chain product velocity both",
  "824": "Over chain product velocity amount",
  "825": "No chain ID for chain merchant",
  "826": "Signature required",
  "827": "Velocity exception error — pay inside",
  "828": "Exceeds merchant count for period — pay inside",
  "829": "Exceeds merchant amount for period — pay inside",
  "830": "Exceeds merchant count and amount for period — pay inside",
  "831": "Exceeds zip code count for period — pay inside",
  "832": "Exceeds zip code amount for period — pay inside",
  "833": "Exceeds zip code count and amount for period — pay inside",
  "834": "Exceeds state count for period — pay inside",
  "835": "Exceeds state amount for period — pay inside",
  "836": "Exceeds state count and amount for period — pay inside",
  "837": "Exceeds global count for period — pay inside",
  "838": "Exceeds global amount for period — pay inside",
  "839": "Exceeds global count and amount for period — pay inside",
  "840": "Unknown velocity error — pay inside",
  "902": "Invalid transaction. This merchant, card or terminal is not permitted to perform this transaction, or the transaction type is invalid, or Fiserv is unable to route a refund request to the network, or there is an issue with the xml message. If a 902 is returned when submitting a completion for the second time, the first completion submitted has been successfully applied, even if the device did not receive a response in the first completion.",
  "903": "Invalid Reversal Transaction — transaction already settled",
  "904": "Format error.",
  "905": "Unsupported message. Transaction was rejected. Call your helpdesk or operations support.",
  "906": "System Error. There is a problem with the host processing system. Call your helpdesk or operations support.",
  "907": "Card issuer or switch inoperative or processor not available",
  "908": "Transaction destination not found for routing.",
  "909": "System malfunction or timeout",
  "911": "Card issuer timed out.",
  "913": "Duplicate transaction.",
  "914": "Void/Full Reversal request unable to process due to settlement already occurred. A Refund transaction may be necessary to reconcile the cardholder's account.",
  "915": "Timeout Reversal not supported. Resend the original transaction with the same Reference Number that timed out. Do not retry the timeout reversal",
  "916": "Void/Full Reversal request unable to process since the Original Authorization was not found.",
  "920": "Security H/W or S/W error — try again",
  "921": "Security H/W or S/W error — no action",
  "923": "Request in progress",
  "924": "Limit check failed",
  "940": "Error.",
  "941": "Invalid issuer.",
  "942": "Customer cancellation",
  "944": "Invalid response",
  "950": "Violation of business arrangement",
  "954": "CCV failed.",
  "958": "CCV2 failed",
  "959": "CAV failed",
  "963": "Acquirer channel unavailable",
};

/** Codes that mean the transaction was approved. */
export const APPROVED_RESPONSE_CODES = new Set(["000", "002", "003", "200"]);

export function isApprovedCode(code: unknown): boolean {
  return APPROVED_RESPONSE_CODES.has(String(code ?? "").trim());
}

/** The raw Fiserv meaning — for logs and support, never shown to a donor. */
export function describeResponseCode(code: unknown): string | undefined {
  return RESPONSE_CODES[String(code ?? "").trim()];
}

const GENERIC = "The payment was declined. Please try a different card, or contact your bank.";

/**
 * Codes the donor can actually act on. Everything absent from this map — including
 * every fraud/security code — returns the generic message above.
 */
const DONOR_SAFE: Record<string, string> = {
  "101": "That card has expired. Please try a different card.",
  "132": "The expiry date doesn't match that card. Check it and try again.",
  "116": "The card was declined for insufficient funds.",
  "134": "The card was declined for insufficient funds.",
  "131": "That card number wasn't recognized. Check the digits and try again.",
  "118": "That card number wasn't recognized. Check the digits and try again.",
  "114": "That account type isn't accepted. Please try a different card.",
  "119": "That card can't be used for this kind of payment. Please try another.",
  "110": "That amount couldn't be processed. Try a different amount.",
  "121": "That amount is over the card's limit. Try a smaller amount or another card.",
  "123": "The card has reached its transaction limit. Try again later or use another card.",
  "100": "Your bank declined the payment. Contact your bank, or try a different card.",
};

/**
 * Codes that mean the ORGANIZATION's gateway setup is wrong, not the donor's card.
 * A donor retrying a different card will never fix these, so they are worth
 * distinguishing: the giving page can tell the donor it isn't their fault and the
 * charity can be alerted.
 */
const MERCHANT_CONFIG_CODES = new Set(["109", "130", "150", "133", "135"]);

export function isMerchantConfigCode(code: unknown): boolean {
  return MERCHANT_CONFIG_CODES.has(String(code ?? "").trim());
}

export function donorMessage(code: unknown): string {
  const key = String(code ?? "").trim();
  if (MERCHANT_CONFIG_CODES.has(key)) {
    return "This organization can't accept card payments right now. Please let them know.";
  }
  return DONOR_SAFE[key] ?? GENERIC;
}
